### PR TITLE
Ternary Search Algorithm

### PR DESCRIPTION
**Pull request by DTBUday**
Added the iterative and recursive method for the ternary search algorithm.

### CODE REVIEW

**Comment by madhavgaba** [comment]
can you give some real time implementation of ternary search?

**Comment by DTBUday** [comment]
Example of this would be the APIO 2015 Palembang Bridges. The analysis can be found [here](http://codeforces.com/blog/entry/43582)

**Comment by madhavgaba** [comment]
looks good, what do you say @AnupKumarPanwar @dynamitechetan ?

**Comment by dynamitechetan** [comment]
Thanks.

**Comment by DTBUday** [comment]
Cheers guys :)

**Pull request merged**
