### PR TITLE
Create subset.cpp

### PR DESCRIPTION
**Pull request by sinkyoungdeok**

### CODE REVIEW

**Comment by kvedala** [comment]
Not really sure what this code is about @sinkyoungdeok 
Please provide some description as to what it is supposed to do.

**Comment by Panquesito7** [comment]
Upstream repository fork has been deleted.

**Comment by fhlasek** [comment]
Closing for inactivity, feel free to re-open and rebase on master if you with to continue on this PR.

**Comment by Swastyy** [comment]
> Closing for inactivity, feel free to re-open and rebase on master if you with to continue on this PR.

@fhlasek Hey! I want to work on this. I have a question that are we counting the number of subsets for which a sum S can be found (subsets will be printed out in this case) or its just that we want to know that if this sum can be created or not?

**Comment by fhlasek** [comment]
@Swastyy I think the original intention of the author was to enumerate, return and print out all the subsets whose sum is the given number S. However, you may also modify the code to count the number of these subsets or just to verify if any such subset exists. It's mostly up to you which direction you decide to take it. I am usually tempted to return the most generic answer that can be obtained by the algorithm without increasing its complexity.

**Pull request closed without merging**
