### PR TITLE
Bubble Sort(Kabarcık Sıralama)

### PR DESCRIPTION
**Pull request by mertkocaa**
About Bubble Sort, bubble sort's working principle, algorithm analysis, best-worst case, such as information has been added. A person entering this pull request can easily learn about bubble sort.
Information about the swap process used in the algorithm is also included in the code. It is explained in the example below to make this process fully understandable.

### CODE REVIEW

**Comment by ashwek** [comment]
@mertkocaa thanx for contributing, it would be great if you could add comments in English.

**Comment by cclauss** [comment]
@nikhilkala Please do not merge PRs if the GitHub Action tests are failing.

**Comment by nikhilkala** [comment]
@cclauss 
Okay, In this case linting issues were there which were already there in the master code, so what should be done in such cases?

**Comment by cclauss** [comment]
Leave the issue open and then ask the submitter if they could please fix the failing tests... https://github.com/TheAlgorithms/C-Plus-Plus/pull/194#issuecomment-618859284

**Pull request merged**
