### PR TITLE
Created a file for divide and conquer

### PR DESCRIPTION
**Pull request by kartikay23**
#### Description of Change
Created a file for solving closest pair of points problem using divide and conquer.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Created a file for solving closest pair of points problem using divide and conquer.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1829"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. **Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6).** 😃

**Review by kartikay23 — COMMENTED** [review]
I have made changes. Please let me know.

**Comment by Panquesito7** [comment]
> I have made changes. Please let me know.

Still not up to the [**repository standards**](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).

**Review by kartikay23 — COMMENTED** [review]
Update the header file in the code.

**Comment by Panquesito7** [comment]
It's still not up to the [**repository standards**](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). 😅

**Pull request closed without merging**
