### PR TITLE
Boost String Algo

### PR DESCRIPTION
**Pull request by icbdubey**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1593"></a>

### CODE REVIEW

**Review by mishraabhinn — COMMENTED** [review]
Do we actually need this? It's not an algorithm. Inbuilt function are being used showcasing nothing. I feel if this would have been done without inbuilt function,  then maybe it could be beneficial for other.  What you guys think @ayaankhan98  and @Panquesito7?

**Review by ayaankhan98 — CHANGES_REQUESTED** [review]
This is really a basic program, it does not contain any algorithm implementation. You are just using the inbuit functions to toggle the letter case. This is not up to the standard of this repository. A better apporach would be to implement these functions which are really basic.

**Comment by ayaankhan98** [comment]
I don't understand whats the need of using boot for such an easy task. It doesn't make any sense to me.

**Comment by Panquesito7** [comment]
I'll close this for now. You can re-open if you think this is an algorithm. 🙂

**Pull request closed without merging**
