### PR TITLE
feat: Created midpoint integration numerical method

### PR DESCRIPTION
**Pull request by ggkogkou**
#### Description of Change
Created midpoint integration numerical method for easy integral approximation.
Tests included (4 functions, integration interval specified).
Correction to the PR #1773 

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Numerical method. Separated this from PR #1773 to match the repositories demands. Participating on hacktoberfest.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1785"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Awesome work! You've done amazing work, and it's been your
first contribution here! We hope you keep contributing! 😄👍🎉

After this PR is merged, you can ask for the
contributor role in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 🚀

**Review by amino19 — APPROVED** [review]

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Could you please fix the CodeQL warnings [**here**](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1785/checks?check_run_id=4058297678)?
Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

**Comment by ggkogkou** [comment]
Done

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Please review @ayaankhan98, @mishraabhinn, and @amino19. Thanks. 🙂

**Review by amino19 — APPROVED** [review]

**Review by amino19 — APPROVED** [review]

**Review by ayaankhan98 — APPROVED** [review]
LGTM! Thanks for your contribution.

**Pull request merged**
