### PR TITLE
fix #765: Doubly Linked List algorithm bug

### LINKED ISSUE #765: [BUG]SegFault in remove(x) DLL
## Description

the remove() function throws a segmentation fault. 

## Expected Behavior

The function should remove the parsed element.

## Actual Behavior

The function fails at "t->prev->next = t->next;" and throws a seg fault

## Possible Fix

Still working on it, just wanted to report it... I don't know C++ well.

## Steps to Reproduce

1. insert some values
2. print if you want
3. delete something

## Context

I was trying to remove a node from the DLL

### PR DESCRIPTION
**Pull request by SamratDe**
Fixed the remove function which was causing segmentation fault while removing first and last elements in the doubly linked list.

### CODE REVIEW

**Comment by SamratDe** [comment]
@ayaankhan98 please check now. I have handled all automated failing tests.

**Comment by cclauss** [comment]
> use class instead of struct

Why is that required??

**Comment by cclauss** [comment]
Is the user warned if the item that they ask to remove is not present?

**Comment by ayaankhan98** [comment]
> > use class instead of struct
> 
> Why is that required??

i think using object oriented concepts code becomes more managable and eaisly understandable if we have a class doubly_linked_list and all the functions associated with this container wrapped within this class

**Comment by SamratDe** [comment]
@ayaankhan98 I have wrapped all functions in a double_linked_list class

**Comment by cclauss** [comment]
> using object oriented concepts code becomes more managable and eaisly understandable

There is a lot of pushback against OOP.  For example the Go language has completely abandoned classes.  So while classes might help, let’s not make them a requirement in all submission.

**Comment by ayaankhan98** [comment]
> > using object oriented concepts code becomes more managable and eaisly understandable
> 
> There is a lot of pushback against OOP. For example the Go language has completely abandoned classes. So while classes might help, let’s not make them a requirement in all submission.

okay sure @cclauss

**Pull request merged**
