### PR TITLE
feat : added library sort 

### PR DESCRIPTION
**Pull request by Perukii**
#### Description of Change

- added library sort (Path : sorting/library_sort.cpp)

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Sort by alphabetical order
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/pull/710/checks?check_run_id=490011886#step:9:46

**Comment by Perukii** [comment]
Do I have more things to do for contributing?

**Comment by cclauss** [comment]
Not that I see.  Let’s just wait for one more positive review before landing this one.

**Comment by cclauss** [comment]
Thanks for your contribution.

**Pull request merged**
