### PR TITLE
Create tree_sort.cpp

### PR DESCRIPTION
**Pull request by shuvam86**
added tree_sort.cpp

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1243"></a>

### CODE REVIEW

**Comment by mishraabhinn** [comment]
[Copied](https://www.geeksforgeeks.org/tree-sort/)
We Don't support plagiarism here. 
Invalid Pull
@kvedala

**Comment by kvedala** [comment]
@mishraabhinn Thank you for your review. Please add the appropriate label so that it becomes easier while viewing in the list.

**Comment by mishraabhinn** [comment]
> @mishraabhinn Thank you for your review. Please add the appropriate label so that it becomes easier while viewing in the list.

I don’t have authority to do that i can only mention that in comment. @kvedala

**Comment by kvedala** [comment]
Got it, thank you, @mishraabhinn

**Pull request closed without merging**
