### PR TITLE
Detect Cycle in Undirected Graph

### PR DESCRIPTION
**Pull request by Sathvik902**
Given an undirected graph, The task is to check if there is a cycle in the given graph.

#### Checklist

- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by Sathvik902** [comment]
Dont know Why I'm getting error in Lint modified file in Awesome CI workflow. Please instruct me what should be done to fix it.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please fix all the [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/4145607587/jobs/7170201216#step:10:44) warnings. After you fix them, we can check the documentation.
Let us know if you need any help with that. 🙂

**Comment by Sathvik902** [comment]
Can you please help me out in this?

**Comment by Panquesito7** [comment]
> Can you please help me out in this?

Sure. Let's discuss this on the [Discord community](https://the-algorithms.com/discord). 🙂

**Pull request closed without merging**
