### PR TITLE
Update best-time-to-buy-and-sell-stock

### PR DESCRIPTION
**Pull request by rudrakshkarpe**
#### Description of Change
Best time to buy and sell a stock is one of the best  Dynamic programming problems, I am glad that I got the opportunity to raise PR for the same.
Looking forward to the fruitful effect of this PR on my Hacktoberfest profile :)

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Review by mishraabhinn — COMMENTED** [review]
Please read this https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md

**Comment by Sanketh149** [comment]
I want to do this as a hacktoberfest contribution
Please assign this to me.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord).** 🙂

**Comment by rudrakshkarpe** [comment]
Unable to join the discord invite

**Comment by Panquesito7** [comment]
> Unable to join the discord invite, the link is broked

Seems the website is down. Try this link for now: https://discord.gg/c7MnfGFGa6

**Comment by rudrakshkarpe** [comment]
Thanks for sharing

**Comment by mishraabhinn** [comment]
I think we can close this pr seems no change ? @Panquesito7 @rudrakshkarpe

**Pull request closed without merging**
