### PR TITLE
Arunabh bit

### PR DESCRIPTION
**Pull request by arunabh-cloud**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1875"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thanks for submitting a PR! 😄 Looks like this is not working. 👀

image

I think we should keep the current test-cases 😅 What do you think?

**Review by arunabh-cloud — COMMENTED** [review]
Hey, 
Thanks for testing my PR.
Here is my understanding.
Going by the logic of the first 3 Test cases:
Case#1  (10, 2 ) == 14  from [ 10 + (2^2) = 14 ]
Case#2  (25, 1) == 27  from  [ 25 + (2^1) =  27 ]
Case#3 (400001, 5) == 400033 from [ 400001 + (2^5) = 400033 ]

So, Case#4 (123, 3) == 131 from [ 123 + (2^3) = 131 ]
Not sure how (123, 3) == 123 ?

**Comment by Panquesito7** [comment]
@aman2000raj, would you like to take a look at this? Thanks. 🙂

**Comment by arunabh-cloud** [comment]
Only the comment on line 67 is incomplete (123,3). 
The Test Case is correct.

**Pull request closed without merging**
