### PR TITLE
Create check_palindrome.cpp

### PR DESCRIPTION
**Pull request by manjur29**
Program for check the number is palindrome or not.

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1295"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

**Comment by xgupta** [comment]
@manjur29  palindrome is already implemented. See https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/others/palindrome_of_number.cpp
You can search Directory.md for what algorithm implementation available.

**Comment by Panquesito7** [comment]
> Palindrome algorithm is already implemented

There can be different implementations for one algorithm;
the name needs to be changed only if it's on the same directory. 🙂

**Comment by xgupta** [comment]
@Panquesito7 If you see the #1201 

> There can be different implementations for one algorithm;

Oh I see both have different implementation. Thanks!

> the name needs to be changed only if it's on the same directory.

This may not be correct if you see [1211](https://github.com/TheAlgorithms/C-Plus-Plus/issues/1211) issue. and [this comment ](https://github.com/TheAlgorithms/C-Plus-Plus/issues/1211#issuecomment-706686596) Where we are having issue with cmake if both files have same name but different directory.

**Comment by xgupta** [comment]
Any updates?

**Review by Panquesito7 — COMMENTED** [review]
> Any updates?

No, it seems the author didn't respond or doesn't want to work on this anymore. You can rework this PR, though. 🙂

**Pull request closed without merging**
