### PR TITLE
Create sleep_sort.cpp

### PR DESCRIPTION
**Pull request by shuvam86**
added sleep_sort.cpp

#### Description of Change
Sleep sorting algorithm is added

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1244"></a>

### CODE REVIEW

**Comment by fhlasek** [comment]
Please add some documentation and briefly describe the algorithm.
Check the [CONTRIBUTING](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) for tips.

**Comment by fhlasek** [comment]
Please only add your own original contributions:
https://www.geeksforgeeks.org/sleep-sort-king-laziness-sorting-sleeping/

**Comment by kvedala** [comment]
Thank you for reviewing @fhlasek. Please add the appropriate label to this pull-request so that it becomes easier to view in the list.

**Comment by fhlasek** [comment]
Sure, will add labels next time! @kvedala Are there any guidelines about reviewing? I'd like to help, but so far been rather chaotic - whenever something caught my attention, I commented here and there. How do we assign reviewers? Is it on first-come-first serve basis?

**Comment by kvedala** [comment]
> Sure, will add labels next time! @kvedala Are there any guidelines about reviewing? I'd like to help, but so far been rather chaotic - whenever something caught my attention, I commented here and there. How do we assign reviewers? Is it on first-come-first serve basis?

Made a brief guideline: https://gitter.im/TheAlgorithms/community?at=5f83112999e1ab4dd1f1d9e8

**Comment by fhlasek** [comment]
Awesome, love it! @kvedala let's check in these guidelines in the repo for persistency.

**Pull request closed without merging**
