### PR TITLE
Added Searching algorithm

### PR DESCRIPTION
**Pull request by abhishek2384**
#### Checklist

- [x] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Review by mishraabhinn — COMMENTED** [review]
https://www.geeksforgeeks.org/search-in-row-wise-and-column-wise-sorted-matrix/
Plagiarism

**Comment by abhishek2384** [comment]
ok

**Comment by CarlosZoft** [comment]
i think this pr can be closed

**Comment by abhishek2384** [comment]
Pls dont spam

**Pull request closed without merging**
