### PR TITLE
added fast_integer_input.cpp

### PR DESCRIPTION
**Pull request by nisshar**
added a useful algorithm to take integer input in c plus plus in a very fast way. it is very useful in competitive programming where cpp is mainly used.

### CODE REVIEW

**Comment by cclauss** [comment]
Automated tests are failing https://github.com/TheAlgorithms/C-Plus-Plus/pull/696/checks?check_run_id=366665566

**Comment by cclauss** [comment]
Please remove line 3 and then use __std::getchars()__ and __std::out__.

**Comment by nisshar** [comment]
what is this ? "Could not find a newline character at the end of the file"

**Comment by cclauss** [comment]
The GitHub Editor is signalling the same thing with the 🚫...
No carrage return at end of file

.cpp files should end with one and only one "__\n__" character.

**Pull request merged**
