### PR TITLE
Count of trailing ciphers in n!

### PR DESCRIPTION
**Pull request by Swastyy**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1521"></a>

### CODE REVIEW

**Comment by Swastyy** [comment]
@mishraabhinn Check this PR once.

**Comment by mishraabhinn** [comment]
> @mishraabhinn Check this PR once.

Why three .cpp files are there to review @Swastyy

**Comment by Swastyy** [comment]
> > @mishraabhinn Check this PR once.
> 
> Why three .cpp files are there to review @Swastyy

I think because they are created from same branch.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please make one PR per file. It'll be much easier to review.

**Comment by mishraabhinn** [comment]
> > > @mishraabhinn Check this PR once.
> > 
> > 
> > Why three .cpp files are there to review @Swastyy
> 
> I think because they are created from same branch.

You can use git restore on other files  which are not needed leaving  count_of_trailing_ciphers_in_factorial_n.cpp

**Comment by Swastyy** [comment]
> > > > @mishraabhinn Check this PR once.
> > > 
> > > 
> > > Why three .cpp files are there to review @Swastyy
> > 
> > 
> > I think because they are created from same branch.
> 
> You can use git restore on other files which are not needed leaving count_of_trailing_ciphers_in_factorial_n.cpp

I think I should make another PR because out of other 2 files one is n-bonacci sequence which is yet to be reviewed and other is cycle sort which is already merged. Since I have used gitpod and it is not in my system git restore wont be possible (maybe 😕 ). If any other option is there tell me @mishraabhinn @Panquesito7

**Comment by Panquesito7** [comment]
Yes, I think you should make another PR, @Swastyy.

**Pull request closed without merging**
