### PR TITLE
Merge sort

### PR DESCRIPTION
**Pull request by Himalay12**
#### Description of Change

Here, I have shorten the code. There are three while loop used in merge function. Among which two of them can be replaced by adding a condition for if and while of first while loop. Now, the condition for while: (i < n1 || j < n2) and for if: (j>=n2 || (i < n1 && L[i]<R[j])).

#### Checklist

- [x] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1066"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1066/checks?check_run_id=1048317975) warnings.

**Comment by Panquesito7** [comment]
Rebase needed.

**Comment by Himalay12** [comment]
How to rebase? How do we write code so we will not get error?

**Comment by Panquesito7** [comment]
See the [GitHub Documentation](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github) for how to resolve conflicts. 🙂

**Comment by Himalay12** [comment]
Replaced two while loop by adding condition in if statement of first while loop of merging.

**Comment by Panquesito7** [comment]
What is this PR about? Please add a brief description in the first post. Thanks.

**Comment by Himalay12** [comment]
I can write here about it.

**Comment by Himalay12** [comment]
Here, I have shorten the code. There are three while loop used in merge function. Among which two of them can be replaced by adding a condition for if and while of first while loop. Now, the condition for while: (i < n1 || j < n2) and for if: (j>=n2 || (i < n1 && L[i]<R[j])).

**Review by Panquesito7 — APPROVED** [review]
LGTM. 👍 😄

**Comment by Himalay12** [comment]
Thank you

**Pull request merged**
