### PR TITLE
Adding implementation for the Boruvka algorithm (finding minimum span…

### PR DESCRIPTION
**Pull request by FranciscoThiesen**
#### Description of Change
In this Pull Request I provide an implementation for the Boruvka algorithm for finding minimum spanning trees. I also provide a test function and a code-block for executing it on graphs provided by the user interactively.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by FranciscoThiesen** [comment]
@Panquesito7 @realstealthninja let me know if any changes are needed, this is an implementation + tests for Boruvka MST algorithm.

Cool fact: This was the first algorithm invented for this particular problem, which is super relevant even today (:

**Comment by FranciscoThiesen** [comment]
@vil02 can you approve my workflows?

**Comment by vil02** [comment]
> @vil02 can you approve my workflows?

I am afraid that only the maintainers of this repository can do that (@realstealthninja, @Panquesito7 could you approve them?).

@FranciscoThiesen if you like I can review your code.

**Comment by FranciscoThiesen** [comment]
@Panquesito7 waiting for review (:

**Comment by FranciscoThiesen** [comment]
@vil02 do you have an idea about how to get this reviewed/merged?

**Pull request closed without merging**
