### PR TITLE
Secant Method

### PR DESCRIPTION
**Pull request by sampatil578**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1117"></a>

### CODE REVIEW

**Comment by sampatil578** [comment]
Suggest Required Changes.

**Comment by kvedala** [comment]
1. This is a good C- code and not a C++ code. 
2. Istn this the same as False-position method? https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/numerical_methods/false_position.cpp

**Comment by Panquesito7** [comment]
@sampatil578 I have seen you are creating many duplicate PR's in this repository.
Please don't spam the repository with creating duplicate PR's and closing them.

If there's something you need help in, just comment, or view the [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1117/checks?check_run_id=1191709251) checks.
See the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) for how to make your algorithm well-documented and refined.

When making changes, don't open new PR's, implement the changes in the same PR.

Thank you.

**Comment by sampatil578** [comment]
> 1. This is a C code and not a C++ code.
> 2. Istn this the same as False-position method? https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/numerical_methods/false_position.cpp

In false position method one point is always fixed in secant method both points are changing at each step.
I have used cout for printing. So, its C++ code not C code.

**Pull request closed without merging**
