### PR TITLE
[feat/fix/docs]: Improve the `dynamic_programming/longest_increasing_subsequence.cpp` file

### PR DESCRIPTION
**Pull request by Panquesito7**
#### Description of Change

- Improve the `dynamic_programming/longest_increasing_subsequence.cpp` file.
  - Added documentation, made the code up to the repository standards, and made the CI stop failing.

#### Checklist

- [x] Added description of change
- [ ] ~Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~
- [ ] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1504"></a>

### CODE REVIEW

**Comment by manncodes** [comment]
Added test and stress test, fixed namespace in  #1505

**Comment by manncodes** [comment]
Check this [file](https://github.com/manncodes/C-Plus-Plus/blob/master/dynamic_programming/longest_increasing_subsequence.cpp) for fixed namespaces and added test and stress test!

PFA stress test file.😄 
[stress_test_file.txt](https://github.com/TheAlgorithms/C-Plus-Plus/files/6614222/stress_test_file.txt)

**Review by ayaankhan98 — COMMENTED** [review]
Longest increasing subsequence is not a new problem in itself, it's bascially a bit extension of Longest common subsequence problem. So, I think we must take this into consideration and modify the code as well as documentation.

##### Limitations of current implementation
- Longest increasing subsequence is also defined by unsorted arrays but this implementation would not be able to find that. It will only work for sorted data.
- Does not shows the relation with it's parent problem that is Longest common subsequence, which is more general. Therefore we must not present it as a new problem in itself rather we must show the relation between the two. This will help people to learn in a better way.
- Does not have separate test function implementation

##### What can we do?
we can modify the implementation in the following way
- Take any array input (sorted or unsorted no matter)
- Sort array in O(n log(n)).
- compute the LCS (Longest common subsequence), This LCS is same as the LIS because we have sorted data.
- Modify the documentation accordingly.

**Comment by Panquesito7** [comment]
@ayaankhan98, in short terms: you're asking to add documentation and improve the code in the Longest Common Subsequence? Sounds good but should probably be done in another PR.

**Comment by ayaankhan98** [comment]
> @ayaankhan98, in short terms: you're asking to add documentation and improve the code in the Longest Common Subsequence? Sounds good but should probably be done in another PR.

I am not saying that we must do this in this PR, that's the reason i didn't requested changes rather i just commented some suggestions which can be taken into consideration in further PRs.

Hope this will clear the issue

**Comment by Panquesito7** [comment]
> > @ayaankhan98, in short terms: you're asking to add documentation and improve the code in the Longest Common Subsequence? Sounds good but should probably be done in another PR.
> 
> I am not saying that we must do this in this PR, that's the reason i didn't requested changes rather i just commented some suggestions which can be taken into consideration in further PRs.
> 
> Hope this will clear the issue

Ah yes, but I was just asking if it's something of high priority or that we should do. Thanks though. 🙂

**Review by ayaankhan98 — APPROVED** [review]

**Comment by Panquesito7** [comment]
I will make some pending **needed** changes to the file before merging. Thanks. 🙂

**Review by ayaankhan98 — APPROVED** [review]

**Pull request merged**
