### PR TITLE
feat: count set bits using lookup table

### PR DESCRIPTION
**Pull request by KartikeySharma**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Proposed an algorithm that counts set bits in an integer in O(1) time using a lookup table that is generated during compile time. Also, it is more efficient than the one already present and has a space complexity of O(1)

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please add `.cpp` at the end of the filename.

**Comment by KartikeySharma** [comment]
done, pls review @Panquesito7

**Comment by KartikeySharma** [comment]
HI @Panquesito7 . it's been 3 days since our last discussion. Please let me know if any other changes are required from my side.

**Comment by Panquesito7** [comment]
Do you still want to work on this PR?

**Pull request closed without merging**
