### PR TITLE
feat: Add aliquot sum of a number algorithm, class Math

### PR DESCRIPTION
**Pull request by SpiderMath**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Opened this PR since I closed #2250 by mistake :frowning: Sorry for the trouble :pensive:

### CODE REVIEW

**Comment by SpiderMath** [comment]
@Panquesito7 Might wanna check this out, I've been sitting on this PR for a while now, since #2250  :no_mouth: :pleading_face:

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Great work! 🚀
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/SpiderMath/C-Plus-Plus_TheAlgorithms/actions

**Comment by SpiderMath** [comment]
> Great work! rocket Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/SpiderMath/C-Plus-Plus_TheAlgorithms/actions

Well, the windows compile checks seem to be failing but not due to any code of mine apparently, going by the error messages

**Comment by SpiderMath** [comment]
@Panquesito7 (>.<)

**Comment by SpiderMath** [comment]
@Panquesito7 hey :grimacing:

**Comment by SpiderMath** [comment]
```
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:139:17: warning: C-style casts are discouraged; use static_cast [google-readability-casting]
        arr, 0, int(std::end(arr) - std::begin(arr)) - 1);
                ^~~
                static_cast<int>
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:139:17: note: FIX-IT applied suggested code changes
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:148:18: error: narrowing conversion from 'typename __normal_iterator<long *, vector<long>>::difference_type' (aka 'long') to signed type 'int' is implementation-defined [cppcoreguidelines-narrowing-conversions,-warnings-as-errors]
        arr2, 0, std::end(arr2) - std::begin(arr2));
                 ^
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:157:18: warning: C-style casts are discouraged; use static_cast [google-readability-casting]
        arr3, 0, int(std::end(arr3) - std::begin(arr3)) - 1);
                 ^~~
                 static_cast<int>
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:157:18: note: FIX-IT applied suggested code changes
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:173:18: warning: C-style casts are discouraged; use static_cast [google-readability-casting]
        arr4, 0, int(std::end(arr4) - std::begin(arr4)) - 1);
                 ^~~
                 static_cast<int>
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:173:18: note: FIX-IT applied suggested code changes
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:182:43: error: narrowing conversion from 'typename __normal_iterator<unsigned long *, vector<unsigned long>>::difference_type' (aka 'long') to signed type 'int' is implementation-defined [cppcoreguidelines-narrowing-conversions,-warnings-as-errors]
    sorting::quick_sort::show(arr_sorted, std::end(arr) - std::begin(arr));
                                          ^
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:185:44: error: narrowing conversion from 'typename __normal_iterator<long *, vector<long>>::difference_type' (aka 'long') to signed type 'int' is implementation-defined [cppcoreguidelines-narrowing-conversions,-warnings-as-errors]
    sorting::quick_sort::show(arr_sorted2, std::end(arr2) - std::begin(arr2));
                                           ^
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:189:31: warning: C-style casts are discouraged; use static_cast [google-readability-casting]
                              int(std::end(arr3) - std::begin(arr3)) - 1);
                              ^~~
                              static_cast<int>
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:189:31: note: FIX-IT applied suggested code changes
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:193:22: warning: C-style casts are discouraged; use static_cast [google-readability-casting]
        arr4_sorted, int(std::end(arr4_sorted) - std::begin(arr4_sorted)) - 1);
                     ^~~
                     static_cast<int>
/home/runner/work/C-Plus-Plus_TheAlgorithms/C-Plus-Plus_TheAlgorithms/sorting/quick_sort.cpp:193:22: note: FIX-IT applied suggested code changes
clang-tidy applied 5 of 5 suggested fixes.
Suppressed 11980 warnings (11980 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
3 warnings treated as errors
Python 3.10.6
12 files were modified.
3 C++ files were modified.
```
Quick sort's erroring out it seems

**Comment by SpiderMath** [comment]
@Panquesito7 (._.)
Man, atleast reply

**Review by Panquesito7 — APPROVED** [review]
Amazing work! Thank you. 🚀

**Comment by SpiderMath** [comment]
> 

That took months :skull:

**Review by tjgurwara99 — APPROVED** [review]

**Pull request merged**
