### PR TITLE
fix: Force to compile FreeGLUT

### LINKED ISSUE #2401: [BUG] Misconfiguration of CMake in the `graphics` folder
### Description

The `graphics` directory uses GLUT (or FreeGlut) to compile. When it cannot find GLUT, it will use FreeGlut instead.
However, it seems that there's a wrong or missing configuration of CMake for that directory.

https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/3595016533/jobs/6054004314#step:4:1248

I tried investigating further for that and tried a few stuff, but none of those changes worked.
I even tried with the old link (which was changed to GitHub at https://github.com/TheAlgorithms/C-Plus-Plus/commit/d0f7f230cad38b7d55a5190a8604b9d649b78910 and it [**worked fine**](https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/3518179849/jobs/5896813163), because it was showing errors in #2396) and it still showed the same error message.

### Expected behavior

CMake should not throw an error message stating that it cannot find `freeglut.lib`.

### Actual behavior

CMake cannot find `freeglut.lib` which makes the CI tests fail.

### Steps to reproduce

_No response_

### Context

This should be fixed immediately as it prevents the Windows checks to verify if the code is running and working as excepted.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
#### Description of Change

Force to compile FreeGLUT to fix #2401

#### Checklist

- [x] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by MaximSmolskiy** [comment]
> Seems the macOS tests are failing eyes https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/3614912354/jobs/6094952417#step:4:562

@Panquesito7 try to delete incorrect GLUT library. When it succeeds, maybe it will help

**Comment by Panquesito7** [comment]
Looks like the CI tests are failing due to another issue. I'll see if I can fix it this week. Thanks.

**Comment by Panquesito7** [comment]
Not sure if this is needed anymore. Looks like the CI is now passing.
Unless FreeGLUT has any advantages over GLUT. @tjgurwara99, thoughts?

**Comment by tjgurwara99** [comment]
Unless we're working with event loops, I don't think there is a benefit to replacing GLUT with FreeGLUT 😄

**Pull request closed without merging**
