### PR TITLE
Replace "\n" -> std::endl

### PR DESCRIPTION
**Pull request by Jxtopher**
Replace "\n" -> std::endl

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1530"></a>

### CODE REVIEW

**Comment by Panquesito7** [comment]
Hmm, which one do you think is better: `\n` or `std::endl`? @ayaankhan98, @mishraabhinn.

**Comment by mishraabhinn** [comment]
> Hmm, which one do you think is better: `\n` or `std::endl`? @ayaankhan98, @mishraabhinn.

Yes. We can use `std::endl`, the only difference it also flush the buffer.

**Comment by Jxtopher** [comment]
See: SL.io.50 (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rio-endl)

"Apart from the (occasionally important) issue of performance, the choice between '\n' and endl is almost completely aesthetic."

**Review by Panquesito7 — APPROVED** [review]
Thanks!

**Pull request merged**
