### PR TITLE
heapsort implementation started at index 1

### PR DESCRIPTION
**Pull request by ericcurtin**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Sort by alphabetical order
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by ericcurtin** [comment]
Will do similar for the C version once this is reviewed/merged

**Comment by bhaumikmistry** [comment]
Please Stick to the format for the Pull request description. @ericcurtin

**Comment by ericcurtin** [comment]
Is it ok now @bhaumikmistry ?

**Comment by bhaumikmistry** [comment]
@ericcurtin Great work!! Since you have touched this file and made it better. Would you mind added a test() function and writing some test check for the functions?

- [ ] Tests

**Comment by ericcurtin** [comment]
Hi @bhaumikmistry is there any example file that does this you could point me towards? I'd like to see the tests actually get executed in the build :) Otherwise it seems like a waste of time.

**Comment by bhaumikmistry** [comment]
> Hi @bhaumikmistry is there any example file that does this you could point me towards? I'd like to see the tests actually get executed in the build :) Otherwise it seems like a waste of time.

You Make a good point @ericcurtin

**Comment by cclauss** [comment]
Perhaps https://github.com/TheAlgorithms/C/tree/master/data_structures/Array shows a model to follow.  There is an __xyz.cpp__ file that contains the algorithm and there is an __xyz_test.cpp__ file that tests the functions in __xyz.cpp__.  We could write a GitHub Action that found all __*_test.cpp__ files and ran them on all pull requests.  Thoughts?

**Pull request merged**
