### PR TITLE
Add EXTRACT_ALL option for doxygen

### PR DESCRIPTION
**Pull request by xgupta**
#### Description of Change

Doxygen is not building some files like backtracking/rate_maze.cpp, backtracking/nqueen_print_all_solutions.cpp etc so enable this help to build them.

#### Checklist

- [x] Added description of change
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1200"></a>

### CODE REVIEW

**Comment by kvedala** [comment]
it has negative implications. After trying the option, it did not work out well.

**Comment by xgupta** [comment]
Thanks for reply! 
So there might be an issue with doxygen comments in those files but I can't figure out. Should I open another issues related to them for generating doxygen documentation?

**Comment by kvedala** [comment]
Are you referring to this issue: https://github.com/TheAlgorithms/C-Plus-Plus/issues/1201 ?

**Comment by kvedala** [comment]
that is because the older contributions do not follow doxygen syntaxes. Only those files are included in the documentation that include a doc block and contain the `@file` tag in it.

**Comment by xgupta** [comment]
Oh, Thanks for explanation. I will fix it.

**Pull request closed without merging**
