### PR TITLE
feat: add HebbLearning algorithm, class hebbLearning

### PR DESCRIPTION
**Pull request by sofia100**
#### Description of Change

Hebb Learning Algorithm is one the simplest algos in Neural Networking. Weights are updated based on the Yin
References: 
https://medium.com/datadriveninvestor/what-is-hebbian-learning-3a027e8e4bbb
https://www.youtube.com/watch?v=n4QxeET2hTo

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and examples, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by kvedala** [comment]
Thank you for your contribution.
1. please do not change the checklist. It is provided for your convenience to follow the repo standards.
2. review all the checklist items and ensure your contribution follows the repo standards and norms

Reviews will be provided only after that.

**Comment by sofia100** [comment]
Thank you for your response.
Can you tell me what and how I need to do exactly?

> 1. please do not change the checklist. It is provided for your convenience to follow the repo standards.

Since I have removed the line in checklist, I am unable to  write it back or act accordingly.

**Comment by mishraabhinn** [comment]
> Thank you for your response.
> Can you tell me what and how I need to do exactly?
> 
> > 1. please do not change the checklist. It is provided for your convenience to follow the repo standards.
> 
> Since I have removed the line in checklist, I am unable to write it back or act accordingly.

r
Don't remove the checklist points. 
Read Contribution guidelines  before contributing.
[Refer](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

**Comment by sofia100** [comment]
> Don't remove the checklist points.

Done
> Read Contribution guidelines before contributing.

Done

**Comment by mishraabhinn** [comment]
> > Don't remove the checklist points.
> 
> Done
> 
> > Read Contribution guidelines before contributing.
> 
> Done

CI workflow is failing. No review will be provided until that is rectified. 
Secondly I don't feel you read the contributing guidelines carefully. 
Thank you. 
r1

**Comment by sofia100** [comment]
Sorry for  the inconvenience caused. 
May be next time onwards I will understand how to do this properly 👍

**Comment by kvedala** [comment]
you can update the code similar to other codes in the repo and the folder. 
[example](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/machine_learning/adaline_learning.cpp)
Note the documentations, organization, etc. 
The repo is meant for codes from which others can learn - as described in the README file for this repo - and not a repo to drop any code.

**Pull request closed without merging**
