### PR TITLE
GitHub Action to run cpplint on all pull requests

### PR DESCRIPTION
**Pull request by cclauss**
Related to #638

#### Checklist

- [ ] Added description of change
- [ ] Added tests and example, test passes
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] Sort by alphabetical order
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by bhaumikmistry** [comment]
Need to fix the old code else, all the future build will be difficult to merge.

**Comment by cclauss** [comment]
Total errors found: 5370  Is it really worth fixing them all?  Are there autoformatters that would do cleanup?  Is there a subset of these issues that are worth fixing?  @tkruse Your advise?

**Comment by cclauss** [comment]
__cpplint --filter=-build,-legal,-readability,-runtime,-whitespace --recursive .__

After this has landed then contributors can remove filters one at a time and fix those issues until we need no more filters.

**Comment by tkruse** [comment]
Sorry for late response. This question is not specific to cpplint, all languages have the same issue when adding a code-checker late to an existing codebase.

My personal preference is to reduce the number of warnings by ignoring the most frequent tolerable ones (i.e. adapting the checker to the "culture" of the project), and fixing the remaining ones. And at some point, huge PRs could be made fixing one of the ignored issues at a time.

**Comment by cclauss** [comment]
Please check out https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/.github/workflows/cpplint_modified_files.yml as a gradual approach to adding linting (and other testing) to the "culture" of a repo.  This runs cpplint __only on those files that have changed__ in a pull request.

**Pull request merged**
