### PR TITLE
Added new Data Structures and String algorithms

### PR DESCRIPTION
**Pull request by aman-garg0001**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1291"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

It is recommended to make one PR per file.
This will make the review process much more faster.

**Comment by aman-garg0001** [comment]
> Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
> Please read them **carefully** and **follow them**.
> 
> It is recommended to make one PR per file.
> This will make the review process much more faster.

My code running well on every machine but your automated compiler is not compiling my codes.
Which compiler are you using?

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Code/documentation is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

**Comment by kvedala** [comment]
> > Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
> > Please read them **carefully** and **follow them**.
> > It is recommended to make one PR per file.
> > This will make the review process much more faster.
> 
> My code running well on every machine but your automated compiler is not compiling my codes.
> Which compiler are you using?

Have you read our [README](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/README.md) and the [CONTRIBUTING](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) files that provide very detailed, itemized explanations and details along with how to execute and test the codes? they are also provided for your convenience in the checklist when creating a pull-request.
Thank you

**Pull request closed without merging**
