### PR TITLE
feat: Create RBTree.cpp

### PR DESCRIPTION
**Pull request by sinkyoungdeok**
Create RBTree.cpp

### CODE REVIEW

**Comment by kvedala** [comment]
@sinkyoungdeok
This is a good code but needs to be updated to the current repo standards.

**Comment by psarvesh** [comment]
Not sure if anyone is working on this. If somebody isn't, can I pick it up?

**Comment by fhlasek** [comment]
@psarvesh absolutely, anyone is welcome to contribute! This PR seems abandoned - you are welcomed to help.

**Comment by ayaankhan98** [comment]
@Panquesito7 @kvedala this is quite an old PR which is not up to the repository standards. I think we can merge this because we don't hay RB tress in data structures. May be someone in future will make another PR to improve this file. Or else it will remain as a stale PR for forever.

**Comment by Panquesito7** [comment]
Not sure about that. It would be nice to merge it, but the code is not properly formatted and it doesn't have refined documentation/code. I think it's OK to merge it; let's wait on @kvedala's response. Thank you. 🙂

**Comment by ayaankhan98** [comment]
> Not sure about that. It would be nice to merge it, but the code is not properly formatted and it doesn't have refined documentation/code. I think it's OK to merge it; let's wait on @kvedala's response. Thank you. 🙂

yup you are right. it's not up to standards of repository, but the point that i want to make is that we have 2 options
- leave this as a stale PR, someday may be it will be closed directly just by seeing that it's quite old.
- Other is to merge this, if this gets included in repository then it's highly likely that someone will improve this in future.

**Comment by ayaankhan98** [comment]
> @sinkyoungdeok
> This is a good code but needs to be updated to the current repo standards.


@Panquesito7 
Kvedala might be busy with other stuff, above quoted text was his earlier response on this PR. i think we can proceede with merging this.

**Pull request merged**
