### PR TITLE
[feat/fix/docs]: Improve code to follow CI/repo rules

### PR DESCRIPTION
**Pull request by Panquesito7**
## Description of Change

Add a bit of documentation in various files. 
Improve code to use C++ standard libraries, and respect repo rules and CI.

This pull request is still WIP.
I will still make more changes.

#### Checklist

- [x] Added description of change
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Forgot to split commits per change, apologizes.

### CODE REVIEW

**Comment by kvedala** [comment]
please split this commit bac4e70 Will be difficult to revert or make any changes otherwise.

**Comment by kvedala** [comment]
> ## Description of Change
> Add a bit of documentation in various files.
> Improve code to use C++ standard libraries, and respect repo rules and CI.
> 
> This pull request is still WIP.
> I will still make more changes.
> 
> #### Checklist
> * [x]  Added description of change
> * [x]  Relevant documentation/comments is changed or added
> * [x]  PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
> * [x]  Search previous suggestions before making a new one, as yours may be a duplicate.
> * [x]  I acknowledge that all my contributions will be made under the project's license.
> 
> Notes: Forgot to split commits per change, apologizes.

Please create separate pull-requests. better for maintenance.

**Comment by Panquesito7** [comment]
Do you mean, separate pull requests for:

- Documentation.
- Fixes.
- Feat.

**Comment by kvedala** [comment]
> Do you mean, separate pull requests for:
> 
> * Documentation.
> * Fixes.
> * Feat.

separate one for each file or a maximum of five related files

**Comment by Panquesito7** [comment]
I'll do as your request when I have time, thanks.

**Comment by kvedala** [comment]
> I'll do as your request when I have time, thanks.

These are good fixes, but disorganized and hence an invitation for new issues.
Splitting them into coherent pulls would benefit the repo. 👍

**Comment by Panquesito7** [comment]
@kvedala is it OK if I create a PR for each small folder (such as `backtracking`)?

**Comment by kvedala** [comment]
> @kvedala is it OK if I create a PR for each small folder (such as `backtracking`)?

that would be better and start with one or two file changes only.

**Pull request closed without merging**
