### PR TITLE
Adding optimized algorithm to check if number is prime or not.

### PR DESCRIPTION
**Pull request by omkarlanghe**
**My first contribution to this repository contains algorithm to check if the given number is prime or not.**

**Small description on how I have optimized the logic:**

- Reduced all possibilities of a number which cannot be prime.

- **Eg**: No even number, except 2 can be a prime number, hence we will increment our loop with i+2 jumping on all odd numbers only.

- If number is <= 1 or if it is even except 2, return false telling number is not prime.

### CODE REVIEW

**Comment by kvedala** [comment]
The repository uses a `clang-format` tool that simplifies the code formatting for you when used with Visual Studio Code. You can check the formatting parameters are: 
`"C_Cpp.clang_format_style": "{BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 80, UseTab: Never}",`

**Comment by omkarlanghe** [comment]
> The repository uses a `clang-format` tool that simplifies the code formatting for you when used with Visual Studio Code. You can check the formatting parameters are:
> `"C_Cpp.clang_format_style": "{BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 80, UseTab: Never}",`

**Comment by omkarlanghe** [comment]
@kvedala  I have removed all tabs and included 4 spaces still I get the error.As, this is my first contribution I don't know how to configure the  format styling.

**Comment by kvedala** [comment]
> @kvedala I have removed all tabs and included 4 spaces still I get the error.As, this is my first contribution I don't know how to configure the format styling.

ok, maybe the IDE you are using is converting spaces back into tabs!?

**Comment by omkarlanghe** [comment]
@kvedala I can still see space seperated indentation in my VS Code.

**Comment by omkarlanghe** [comment]
image

Why Am I getting this error, even if I have followed all coding, naming convention guidelines from contribution document. Am I doing anything wrong ?

**Comment by kvedala** [comment]
> image
> 
> Why Am I getting this error, even if I have followed all coding, naming convention guidelines from contribution document. Am I doing anything wrong ?
> My file does not contain any upper case letter.

The folder name should be ‘math’ and not ‘Math’

**Comment by omkarlanghe** [comment]
@kvedala Yes, I solved the issue. It was a folder issue, Which i got to know after reading the complete contribution guide of the repository.
Thank you for you guidance.

**Pull request closed without merging**
