### PR TITLE
Add CmakeList.txt for greedy_algorithms, operations_on_datastructures, range_queries to build their bin

### PR DESCRIPTION
**Pull request by xgupta**
#### Description of Change

fix [issue 1211](https://github.com/TheAlgorithms/C-Plus-Plus/issues/1211)
Add CmakeList.txt for greedy_algorithms, operations_on_datastructures, range_queries to build their bin. Also fix bugs related to them.
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1234"></a>

### CODE REVIEW

**Comment by xgupta** [comment]
So, I see some checks are failing fro four files. I will try to fix them and update the pull request soon.  operations_on_datastructures/union_of_2_arrays.cpp and operations_on_datastructures/intersection_of_2_arrays.cpp are easy to fix. Third ad fourth need rewriting using std::cout, std::cin and some other fixes. In range_queries/mo.cpp can we use cmath header there or not?

**Comment by xgupta** [comment]
Anyone can help with range_queries/mo.cpp. Algorithm is building correctly and when running gives segmentation fault. code formater gives an error "do not declare C-style arrays, use std::array<> instead" with query struct. If someone looks at the diff and tell how can I resolve this error. I tried replacing it with std::vector. But then this produces an error in the sort function where the + operator is applying to vector and int. error message is "mo.cpp:49:20: error: invalid operands to binary expression ('std::vector<query>' and 'int')".

**Comment by kvedala** [comment]
> Anyone can help with range_queries/mo.cpp. Algorithm is building correctly and when running gives segmentation fault. code formater gives an error "do not declare C-style arrays, use std::array<> instead" with query struct. If someone looks at the diff and tell how can I resolve this error. I tried replacing it with std::vector. But then this produces an error in the sort function where the + operator is applying to vector and int. error message is "mo.cpp:49:20: error: invalid operands to binary expression ('std::vector' and 'int')".

As described in my comment here: https://github.com/TheAlgorithms/C-Plus-Plus/issues/1211#issuecomment-704953097, it is a multi step process. Before you create a "fix", discuss a strategy for how-to in comments at #1211. 
A fool-proof way to resolve it would be to fix one individual file at a time. Then and only then can the CMakeLists.txt be added to the folder without creating a plethora of errors.

**Comment by xgupta** [comment]
closing for now and will send separate pull request.

**Pull request closed without merging**
