### PR TITLE
Added mod_inverse_by_fermat_theorem.cpp in math directory.

### PR DESCRIPTION
**Pull request by mann2108**
#### Description of Change

Finding modular inverse using Fermat Little Theorem.

Fermat's Little Theorem state that => ϕ(m) = m-1, where m is prime number.

(a * x) ≡ 1 mod m.
x ≡ (a^(-1)) mod m.
Using Euler's theorem we can modify the equation.
(a^ϕ(m)) ≡ 1 mod m (Where '^' denotes the exponent operator)

Here 'ϕ' is Euler's Totient Function. For modular inverse existence 'a' and 'm' must be relatively primes numbers.

To apply Fermat's Little Theorem is necessary that 'm' must be a prime number.
Generally in many competitive programming competitions 'm' is either 1000000007 (1e9+7) or 998244353.

We considered m as large prime (1e9+7).
(a^ϕ(m)) ≡ 1 mod m (Using Euler's Theorem)
ϕ(m) = m-1 using Fermat's Little Theorem.
(a^(m-1)) ≡ 1 mod m
Now multiplying both side by (a^(-1)).
(a^(m-1)) * (a^(-1)) ≡  (a^(-1)) mod m
(a^(m-2)) ≡  (a^(-1)) mod m

We will find the exponent using binary exponentiation. Such that the algorithm works in O(log(m)) time.

 Example: -
 a = 3 and m = 7
 (a^(-1) mod m) is equivalent to (a^(m-2) mod m)
 (3^(5) mod 7) = (243 mod 7) = 5
 Hence, ( 3^(-1) mod 7 ) = 5
 or ( 3 * 5 ) mod 7 = 1 mod 7 (as a*(a^(-1)) = 1)

#### Checklist

- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] Sort by alphabetical order
- [X] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by poyea** [comment]
Looks good. I've tested with some numbers. Is it possible to add some examples in the comment? Also can `m` be a parameter as well? We may have to check if it is a prime though.

**Comment by mann2108** [comment]
> Looks good. I've tested with some numbers. Is it possible to add some examples in the comment? Also can `m` be a parameter as well? We may have to check if it is a prime though.

That seems good to me too. I have committed the changes as requested.

**Comment by mann2108** [comment]
@poyea Can we merge this PR?

**Comment by poyea** [comment]
sure!

**Pull request merged**
