### PR TITLE
fix, test: simplification and tests for number_of_positive_divisors

### PR DESCRIPTION
**Pull request by fhlasek**
#### Description of Change

- The function was not actually implemented according to the description and didn't handle negative inputs correctly (it was only checked in the main function).
- The function unnecessarily created a vector of numbers only to multiply them later, these numbers can be multiplied as you go.
- Fixed a typo in the description.
- Adding some unit tests.

#### Checklist

- [X] Added description of change
- [X] Added tests and example, test must pass
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

Notes: 
A small refactor of this module.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/975"></a>

### CODE REVIEW

**Comment by kvedala** [comment]
The error is because the Checksum of a file has changed on their release servers. It has been fixed on the master branch.

**Comment by kvedala** [comment]
> The error is because the Checksum of a third-party file has changed on their release servers. It has been fixed on the master branch.

Further review revealed that the website the file is retrieved from - source forge - is currently facing issues and hence the build is failing on windows. Hope they resolve the issue soon.

**Comment by kvedala** [comment]
can you please merge the latest `upstream/master` branch and push. thanks

**Comment by Panquesito7** [comment]
@kvedala AFAIK, if the PR gets merged without applying #979, the build will pass after being merged. 🙂

**Comment by fhlasek** [comment]
Thanks @kvedala and @Panquesito7 . CI passes now.

**Pull request merged**
