### PR TITLE
bugs: fix warnings in matrix_exponentiation

### PR DESCRIPTION
**Pull request by kvedala**
#### Description of Change

Part of effort in #880 
Fixes global variables in `matrix_exponentiation.cpp`. The program execution, input and output is unknown.

#### Checklist

- [x] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by kvedala** [comment]
@stepfencurryxiao was the original author and should review and provide fixes, documentation and corrections in the code

**Comment by kvedala** [comment]
> Looks good. Should we document it too or wait for the original authors before merging?

@tjgurwara99 It would be awesome If you can document it. you create a new pull-request once I merge this

**Comment by kushagra98** [comment]
Oh Okay. It's fine now!

**Comment by kvedala** [comment]
> Oh Okay. It's fine now!

@kushagra98 it unfortunately isn't all fine. The program is incomprehensible to understand:
1. exponentiation - where and how is this happening. comments would be needed
2. input and output - how are the inputs structured? what is the program expecting and in the output, what is the expected output
3. per the repo standards, the program requires to have self-tests. See #894 for example.
Thank you

**Comment by kushagra98** [comment]
Okay. I'll look into it and fix the things up!

**Comment by kushagra98** [comment]
Okay so first of all this technique is used to solve linear equations.
Example:

- Fibonacci series, F(n) = F(n-1) + F(n-2).

- Or any other series like F(n) = 2*F(n-1) + 3*F(n-2) + 4

These linear equations/recurrences can be solved using:

1. Recursion - It takes exponential time to calculate. For calculating the Nth term of the Fibonacci series, it will take O(2^N).

2. Dynamic Programming - It takes linear time to calculate. For calculating the Nth term of the Fibonacci series, it will take O(N).

3. Matrix Exponentiation - It takes logarithmic time to calculate. For calculating the Nth term of the Fibonacci series, it will take O(log(N)).

**Comment by kushagra98** [comment]
> > Oh Okay. It's fine now!
> 
> @kushagra98 it unfortunately isn't all fine. The program is incomprehensible to understand:
> 
> 1. exponentiation - where and how is this happening. comments would be needed
> 2. input and output - how are the inputs structured? what is the program expecting and in the output, what is the expected output
> 3. per the repo standards, the program requires to have self-tests. See #894 for example.
>    Thank you


1. The exponentiation part is where I'm calculating the **power** of a matrix. Say I have to calculate the A^N where A is a matrix and N is some number. Then A^N is being calculated in Time complexity of O(log(N) * time_to_multiply_two_matrices). This is where exponentiation works.

2.  The problem statement here I'm taking is general for any linear equation. The problem says that:
The sequence A<sub>i</sub> is defined as follows:

    - A<sub>i</sub> = B<sub>i</sub> (for i <= k)

    - A<sub>i</sub> = C<sub>1</sub>A<sub>i-1</sub> + C<sub>2</sub>A<sub>i-2</sub> + ... + C<sub>k</sub>A<sub>i-k</sub> (for i > k)
  
    Since the answer can be very large it is calculated modulo 10<sup>9</sup>.

    I'm taking an input T i.e. is the number of test cases. Each test case solves such linear recurrences.
    In each test case, the program wants input for K.
    Then it asks for all the B's that are described above.
    Then it asks for all the C's that are described above.
  
3. I'll look into this thing.

**Comment by kvedala** [comment]
@kushagra98 Thank you for the info. People studying the code wouldn’t be checking this issue and the comment above. I suggest the info provided be included in the file itself as comments in the Doxygen format so that the automated tools will generate a proper documentation for this code.

**Pull request merged**
