### PR TITLE
feat: add pancake sorting algorithm

### PR DESCRIPTION
**Pull request by AbhishekAjoy**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] Sort by alphabetical order
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by cclauss** [comment]
`cpplint_modified_files` tests are failing.  Please click the `Details` link to the right of the ❌ below.

**Comment by cclauss** [comment]
Did you mean to close this?

**Comment by AbhishekAjoy** [comment]
I had made another pull request.

**Comment by kvedala** [comment]
@abhishek-987 please keep only one pull-request - it will help everyone keep a track of the file changes and better help you to contribute. 
In your comment you mentioned necessary changes were made but if they are not in this same pull-request, we would have to recheck the complete file all over again!
You can close the other pull-request, reopen and continue this pull-request.

**Comment by AbhishekAjoy** [comment]
This is the pull request i would like to merge. The other one was closed.

**Comment by abhishek-987** [comment]
@AbhishekAjoy 😊

**Pull request closed without merging**
