### PR TITLE
feat: Add some `std::endl` in `hashing/chaining.cpp`

### PR DESCRIPTION
**Pull request by piyush168713**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1556"></a>

### CODE REVIEW

**Comment by piyush168713** [comment]
is std::endl is more faster than endl  ?????

**Comment by Panquesito7** [comment]
`std::endl` should be used instead of `endl`.

**Comment by Swastyy** [comment]
@piyush168713 You cannot use any member function without specifying its namespace.

**Comment by Swastyy** [comment]
I think this PR can be closed now @Panquesito7

**Comment by piyush168713** [comment]
@Swastyy , thankuh for you response..

**Pull request closed without merging**
