### PR TITLE
[enhancement] New Graphics implementation with algorithm for spirograph

### PR DESCRIPTION
**Pull request by kvedala**
#### Description of Change

* Implementation to generate curves of spirograph
* Functions to plot curve resulting from the specs to a CSV file that can be read and plotted 
* Function to check for OpenGL and GLUT libraries to create a window and perform animation of the curves for various input parameters.
* Gitpod
    * Enable graphics compilation
    * Enable VNC to view GUI

#### Rationale for choosing FreeGLUT:

* Provides a UI wrapper for various OS
* Is a full replacement of much older, the original GLUT
* More evolved and in maintenance than original GLUT
* All OpenGL code still needs to be implemented by the programmer

#### Testing

Implementation tested with and without OpenGL on Windows, Linux and MacOS. Also expected to work on Android and Blackberry OS.
Note that this can run without OpenGL. If GLUT library is available, will automatically compile for OpenGL.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

#### Notes: 
Should this be considered as an algorithm for this repo?

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/936"></a>

### CODE REVIEW

**Comment by kvedala** [comment]
@tjgurwara99 @ayaankhan98 @mishraabhinn @Panquesito7 @cclauss @deadshotsb @ashwek 
Do you guys think this contribution would be a good add to the repo? It may not seem like an algorithm but a good reference to implement quick graphics for plots, etc. with documentation.

**Comment by kvedala** [comment]
> yes i personally think it would be nice to include graphics content either graphics algorithms or some other amazing graphics content in this repository, it will help the learners and encourage them to get started with libraries like OpenGL, SDL etc.

The repository goals seem to be to provide educational information to program algorithms in C++. OpenGL is a primitive and fundamental whether using a library or not. SDL, thought popular and good for writing games, is an independent library that does not add much value to the objectives of the repo. Creating programs in SDL will make this folder into an "examples for SDL" type folder which is what I think we should continuously avoid. Hence, only OpenGL 😄

**Comment by ayaankhan98** [comment]
> > yes i personally think it would be nice to include graphics content either graphics algorithms or some other amazing graphics content in this repository, it will help the learners and encourage them to get started with libraries like OpenGL, SDL etc.
> 
> The repository goals seem to be to provide educational information to program algorithms in C++. OpenGL is a primitive and fundamental whether using a library or not. SDL, though popular and good for writing games, is an independent library that does not add much value to the objectives of the repo. Creating programs in SDL will make this folder into an "examples for SDL" type folder which is what I think we should continuously avoid. Hence, only OpenGL

i am not enforcing the constraints we must do these things, i had just given example. ; )

**Comment by kvedala** [comment]
> > yes i personally think it would be nice to include graphics content either graphics algorithms or some other amazing graphics content in this repository, it will help the learners and encourage them to get started with libraries like OpenGL, SDL etc.
> 
> The repository goals seem to be to provide educational information to program algorithms in C++. OpenGL is a primitive and fundamental whether using a library or not. SDL, though popular and good for writing games, is an independent library that does not add much value to the objectives of the repo. Creating programs in SDL will make this folder into an "examples for SDL" type folder which is what I think we should continuously avoid. Hence, only OpenGL 😄

Rationale for using FreeGLUT:
* Provides a UI wrapper for various OS
* Is a full replacement of much older, the original GLUT 
* More evolved and in maintenance than original GLUT
* All OpenGL code still needs to be implemented by the programmer

**Comment by cclauss** [comment]
Nice little tool... https://sciencedemos.org.uk/spirograph.php

**Comment by kvedala** [comment]
> https://sciencedemos.org.uk/spirograph.php

Yes. Now do it in C 😄 
Very easy to implement in WebGL - but again, the fundamentals are the algorithm:
* to implement the function and 
* convert the function to OpenGL constructs

**Comment by Panquesito7** [comment]
Sorry for long reply; sounds good to me. 👍

**Pull request merged**
