### PR TITLE
optimized space-complexity from O(m*n) to O(n) in edit-distanceprogram

### PR DESCRIPTION
**Pull request by arpanbhatt**
#### Description of Change
<
**Optimized space-complexity from O(m*n) to O(n) in edit-distance program**
I have added the function editDistDP_in_O_n_space in edit-distance program under dynamic-programming section. This function will use O(n) space complexity instead of O(m*n) space complexity to calculate the answer.
>

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)

- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: <Reduced the space complexity from O(m*n) to O(n)>

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1257"></a>

### CODE REVIEW

**Comment by arpanbhatt** [comment]
Proper Documentation has been done
Please review the code.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Documentation is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) yet.
You can also refer to the [Doxygen Guidelines](https://www.doxygen.nl/manual/docblocks.html) for how to document your code. 🙂

**Comment by arpanbhatt** [comment]
@Panquesito7 please review the code. I have made proper changes.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Documentation is not up to the [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html).
Please read them **carefully** and **follow them**.

**Pull request closed without merging**
