### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by JosephTLyons**
I don't believe C++ allows for variables length arrays, so I implemented a dynamic array with a pointer.  I also cleaned up formatting a tiny bit.

### CODE REVIEW

**Comment by JosephTLyons** [comment]
There are others that seem to be using VLAs as well.. if this pull request is accepted, I will fix the others as well.

**Comment by JosephTLyons** [comment]
This can be closed if there is no interest in accepting the changes.

**Comment by christianbender** [comment]
@JosephTLyons  C++ contains some useful data structures in its standard library. These includes dynamic arrays such as Vectors.

**Comment by JosephTLyons** [comment]
Yes, if you use a vector, you’re fine, if you allocate an array through a pointer, you’re fine, but to my knowledge, you cannot have VLAs outside of these two structures in C++17.

**Pull request closed without merging**
