### PR TITLE
docs: fix typo in binary_search docs

### PR DESCRIPTION
**Pull request by shanekadish**
#### Description of Change

The docs for the `binary_search` function say that input parameter array `a` is the 'array to sort'. I believe this should say 'array to **search**', since the function _searches_ the array, and doesn't sort it.

#### Checklist

- [x] Added description of change
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

Change 'sort' to 'search' in docs for the `binary_search` function.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1572"></a>

### CODE REVIEW

**Review by ayaankhan98 — APPROVED** [review]
:+1:  @shanekadish

**Review by Panquesito7 — APPROVED** [review]
Great catch, @shanekadish! Thanks for your contribution. 🚀

**Comment by Panquesito7** [comment]
Hmm, it seems that this change is making the CI fail. @ayaankhan98, should I start working on fixing that file?

**Comment by ayaankhan98** [comment]
> Hmm, it seems that this change is making the CI fail. @ayaankhan98, should I start working on fixing that file?

Yes sure, resolve the issue.

**Review by KukretiShubham — APPROVED** [review]

**Comment by 3kDo50J** [comment]
kuunuu anshaarallaah

**Pull request closed without merging**
