### PR TITLE
Added Eulers Totient Function in math directory

### PR DESCRIPTION
**Pull request by mann2108**
#### Description of Change

In _Number Theory_, **Euler's Totient Function** counts the positive integers up to given integer n that are relatively prime to n. It is written using the Greek letter _phi_ as φ(n) or ϕ(n), and may also called Euler's Phi Function. In other words, it is the number of integers k in the range 1<= k <= n for which the greatest common divisor gcd(n,k) is equal to 1.

This algorithm is implemented in O(sqrt(n)) time complexity and O(1) space complexity respectively.

This algorithm follows like this: - 

phi(n) = phi(p1^a1) * phi(p2^a2)...
where p1, p2,... are prime factor of n.

3 Euler's Property:
1. phi(prime_no) = prime_no-1
2. phi(prime_no^k) = (prime_no^k - prime_no^(k-1))
3. phi(a,b) = phi(a) * phi(b) where a and b are relative primes.

Applying this 3 property on the first equation.
phi(n) = n * (1-1/p1) * (1-1/p2) * ...
where p1,p2... are prime factors.

Example Test Cases: - 
n = 9
Therefore there are total 6 numbers that are relatively prime to 9.
1, 2, 4, 5, 7 and 8.
**_φ(9) = 6_**

#### Checklist

- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#New-File-Name-guidelines)
- [X] Added tests and example, test must pass
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Sort by alphabetical order
- [X] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by mann2108** [comment]
@cclauss Is there anything left in contributing?

**Comment by cclauss** [comment]
My approval means that this submission looks good to me.

**Comment by mann2108** [comment]
This is my first contribution toward _TheAlgorithms_, I want to know when my PR will merge?

**Comment by cclauss** [comment]
I have asked a few other folks to review...  The last time that I wrote C++ in anger was decades ago.

**Comment by mann2108** [comment]
@poyea @cclauss Thank you looking forward to contribute more.

**Pull request merged**
