### PR TITLE
Use getchar over getch

### PR DESCRIPTION
**Pull request by ericcurtin**
getch in Windows specific. Now the code will compile
and work on other platforms like Linux and macOS.

### CODE REVIEW

**Comment by ericcurtin** [comment]
Should I fix the linting problems in this PR or another PR? The linting problems are from pre-existing code.

**Comment by cclauss** [comment]
Please fix these cpplint issues: https://github.com/TheAlgorithms/C-Plus-Plus/pull/681/checks?check_run_id=350446431#step:9:46

**Comment by ericcurtin** [comment]
Did you mean to put a space in the filename? "heap_sort .cpp"

**Comment by ericcurtin** [comment]
Linting problems fixed but it doesn't seem to like the rename.

**Comment by cclauss** [comment]
Thanks much.

**Pull request merged**
