### PR TITLE
feat : update cmake version

### LINKED ISSUE #2479: [FEATURE] Update CMake to a newer version
### Detailed description

It appears the version we're currently using is 3.9.0, which was released in [July 2017](https://cmake.org/pipermail/cmake/2017-July/065814.html).
I think it'd be great if we could update to a newer (or the latest) version, to have more security fixes, features, and as well as being up-to-date and ensure our project works with the latest versions.

### Context

This will ensure we have the latest security fixes and features, and make sure our project works with the latest versions of CMake.

### Possible implementation

Upgrade CMake to a newer or the latest version (the current version is 3.9.0).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by heysujal**
#### Description of Change

I have updated the cmake version in CMakeLists.txt
Closes #2479
#### Checklist

- [X] Added description of change
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Weird. It appears there's some sort of weird error for the macOS runs. We might need to update some other framework or tool that supports CMake or use 3.26.3 instead.
https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/5279661483/jobs/9557307688#step:3:7

**Comment by realstealthninja** [comment]
the latest run seems to be fine @Panquesito7

**Comment by realstealthninja** [comment]
the test just completed as success. restarting it seemed to have fixed it!

**Review by realstealthninja — DISMISSED** [review]
looks good!

**Comment by heysujal** [comment]
earlier it was giving error

**Comment by realstealthninja** [comment]
> earlier it was giving error

not anymore :smile:  it was probably some timing issue

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thanks! 🚀

**Comment by Panquesito7** [comment]
Looks like the error is back: https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/5294580234
If the error persists, I recommend reverting this PR or trying to use 3.26.3. It wouldn't really harm, IMO.

**Comment by heysujal** [comment]
I only made changed in CMakeLists.txt and i didn't change any other file . But it my pull request it is showing some other files as well with some changes

**Comment by vil02** [comment]
This PR not only breaks some of the workflows but also gitpod:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.26.4 or higher is required.  You are running version 3.21.4
```

I would recommend to revert this change. CMake has pretty good backwards compatibility, so the only reason which I see to to update `cmake_minimum_required(...)` is that you want to use a new CMake feature in the project. Or is there something what I am missing?

**Comment by Panquesito7** [comment]
Will revert for now. We can always do it again or see any other workarounds. 🙂

**Comment by heysujal** [comment]
@Panquesito7 Got it

**Pull request merged**
