### PR TITLE
Create pigeonholesort.cpp

### PR DESCRIPTION
**Pull request by NourBc**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Sort by alphabetical order
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/pull/737/checks?check_run_id=622410241#step:9:46

**Comment by cclauss** [comment]
For readability the file needs indentation (four spaces) please.

**Comment by cclauss** [comment]
Do we need all these single character or two character variable names?  Longer variable names will make the code much more readable.

**Comment by nourrrrrrrr** [comment]
> For readability the file needs indentation (four spaces) please. Also...

When i added the indentations, i got other errors, 
I will try to fix everything thank you.

**Comment by cclauss** [comment]
The linter seem to have issues with variable that start with lower case `k`.
sorting/pigeonholesort.cpp:20:  Do not use variable-length arrays.  Use an appropriately named ('k' followed by CamelCase) compile-time constant for the size.  [runtime/arrays] [1]

**Pull request closed without merging**
