### PR TITLE
Update Bubble Sort.cpp

### PR DESCRIPTION
**Pull request by Indrumon**
Improved performance and reliability along with good coding practices

#### Checklist

- [x] Added description of change
- [ ] Added tests and example, test passes
- [x] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] Sort by alphabetical order
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by cclauss** [comment]
Please address __cpplint__ issues: https://github.com/TheAlgorithms/C-Plus-Plus/pull/675/checks?check_run_id=331505254#step:7:41

**Comment by cclauss** [comment]
Also, please rename the file from __sorting/Bubble Sort.cpp__ to __sorting/bubble_sort.cpp__ (lowercase, no spaces).

**Comment by bhaumikmistry** [comment]
@Indrumon Since you are making change to the file.
consider
- [ ] removing the sort code out of main() and make it a function out of it.
- [ ] add predefined data and test the sort function as well.

**Comment by Indrumon** [comment]
@bhaumikmistry This is my first time trying GitHub to contribute to open source projects and I'm afraid that I've messed up... I was just trying to make some positive ammendments to that code but ended up being lashed for reasons I don't understand like cpplint, etc...

**Comment by bhaumikmistry** [comment]
@Indrumon Do not be afraid of the checks and the rules. They are there to maintain the quality standards. please check the links provided in the action sections. This way you can learn how to contribute. Feel free to ask for clarification.

**Comment by Indrumon** [comment]
@bhaumikmistry Thank you sir :D I appreciate your help and I'll return to GitHub once I learn to use it with a team on some real projects. As of now, I'm just a student who has worked on only individual projects to enhance my development skills but I'll also look into GitHub tutorials to upgrade my team-coding skills as well :)

**Pull request closed without merging**
