### PR TITLE
Add file for non-recursive merge sort

### PR DESCRIPTION
**Pull request by Albirair**
Add the source file (sorting/non_recursive_merge_sort.cpp) which defines the function template "non_recursive_merge_sort" in different forms, along with a helper function merge. Moreover, it creates 2 additional files, doxy.txt for Doxygen configuration, and a makefile to automate building, testing and cleaning. This address [issue #728](https://github.com/TheAlgorithms/C-Plus-Plus/issues/728).

### CODE REVIEW

**Comment by cclauss** [comment]
Please click on the ˋDetails` next to the ❌ to see why the tests are failing.

**Comment by cclauss** [comment]
The GitHub Action seem to fail on `make doc`.

**Comment by Albirair** [comment]
`make doc` generates the documentation using "Doxygen" in order to use it, Doxygen has to be installed on the computer.

**Comment by cclauss** [comment]
The docs are getting generated and pushed into https://github.com/TheAlgorithms/C-Plus-Plus/tree/gh-pages/html but I really have no idea how to get them into https://thealgorithms.github.io or https://thealgorithms.github.io/C-Plus-Plus

**Comment by kvedala** [comment]
Should this be closed?

**Pull request merged**
