### PR TITLE
Created SleepSort.cpp

### PR DESCRIPTION
**Pull request by navdeepkk**
This is an implementation of Sleep Sort algorithm in C++.

### CODE REVIEW

**Comment by navdeepkk** [comment]
@yashbansal6 Please merge this with master.

**Comment by cclauss** [comment]
Please use four spaces instead of tabs for indentation.

**Comment by navdeepkk** [comment]
Test Failing because pthread library is not linked.

**Comment by navdeepkk** [comment]
Please merge this with master.

**Comment by cclauss** [comment]
TheAlgorithms/Python#2352

**Pull request closed without merging**
