### PR TITLE
Create Prim.cpp

### PR DESCRIPTION
**Pull request by Himanshu-77**
Created file for Prim's Algorithm in graph that was still missing.

### CODE REVIEW

**Comment by Himanshu-77** [comment]
Can anybody tell me , why i am getting 1 check failed - cpplint_modified_files . I have tested my code on so many test cases , checked indentation and much more. But still getting one check failed with exit status 1.

**Comment by cclauss** [comment]
Click the __Details__ button as the twisty next the the ❌ to see...
```
 1 files contain uppercase characters:
graph/Prim.cpp
```

**Comment by Himanshu-77** [comment]
Thank you @cclauss for your contribution. Now waiting for merging it

**Comment by ayaankhan98** [comment]
@cclauss can we merge this with master?

**Pull request merged**
