### PR TITLE
Quicksort

### PR DESCRIPTION
**Pull request by Himalay12**
#### Description of Change

Not require swapping outside loop in partition function just run loop till high.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1419"></a>

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Why was `sorting/merge_sort.cpp` removed?
Also, what is the `sorting/merge_sort` file for?

**Comment by Himalay12** [comment]
i had use there only one array. it was causing error so i removed it.

**Comment by Himalay12** [comment]
i will update it later.

**Comment by Himalay12** [comment]
Could you make review for quicksort? I have participated in hactoberfest 2020. And it will counted there.

**Pull request closed without merging**
