### PR TITLE
fix: Insert() data_structure Binary Search Tree bug

### PR DESCRIPTION
**Pull request by liushubin-gitHub**
in method: void Insert(node *n, int x) ,
we should insert a node to the right of a Binary Search Tree.

### CODE REVIEW

**Comment by liushubin-gitHub** [comment]
current method always insert a new node to the left.
maybe a mistake of the author:)

**Comment by kvedala** [comment]
no documentation anywhere. The code should be "educational" i.e., people reading it should be able to "learn" from it.

**Comment by kvedala** [comment]
Please present your test cases where:
1. existing code failed
2. fixes made resolve the above fail cases

**Comment by liushubin-gitHub** [comment]
> Please present your test cases where:
> 
> 1. existing code failed
> 2. fixes made resolve the above fail cases

This is the original bugfix modify. I hope all confuse will be clear.
https://github.com/TheAlgorithms/C-Plus-Plus/pull/813

**Comment by kvedala** [comment]
> > Please present your test cases where:
> > 
> > 1. existing code failed
> > 2. fixes made resolve the above fail cases
> 
> This is the original bugfix modify. I hope all confuse will be clear.
> #813

Thank you @liushubin-gitHub But the reference pull-request does not answer the questions I asked for. I reiterate:
1. existing code failed
2. fixes made resolve the above fail cases

**Comment by liushubin-gitHub** [comment]
suppose a test case: root->value = 1; insert(0);

**Comment by liushubin-gitHub** [comment]
suppose a test case: 
initial root->value = 1; 

insert(0);//insert left of tree
insert(２);//should insert right of tree，
//but actual still insert to the left. That is the problem.

#813
Fix: change left to right

**Comment by liushubin-gitHub** [comment]
is there any other problem?

**Comment by kvedala** [comment]
> @kvedala
> 
> REPRODUCTION CASE:
> 1、root->val = 1; //add root node with value 1
> 
> 2、insert(0); //insert a new node
> 3、insert(2);
> 
> Expect:
> The new node 0 insert to left of tree，new node 2 insert to right
> 
> In fact:
> new node 2 still insert to the left. That is the problem.(in fact,all node will be insert to left of the tree)
> 
> #813
> Fix: change root->left to root->right

Thank you for the examples. 👌 
In the original implementation, all nodes were added to the right and hence it worked. Does it make a difference in the result of the tree search algorithm?

**Comment by liushubin-gitHub** [comment]
i think the author want to make a normal binary tree with big nodes right and small nodes left.

**Comment by kvedala** [comment]
@cclauss As the author of the original implementation, could you please ensure the validity of the changes? Thank you

**Comment by cclauss** [comment]
I was not the original author.  @christianbender was [according to git history](https://github.com/cclauss/C-Plus-Plus/blame/b8fbfb5dbba75baf1176d8d600a29488f336e862/data_structure/Binary%20Search%20Tree.cpp).

**Comment by kvedala** [comment]
> I was not the original author. @christianbender was [according to git history](https://github.com/cclauss/C-Plus-Plus/blame/b8fbfb5dbba75baf1176d8d600a29488f336e862/data_structure/Binary%20Search%20Tree.cpp).

Ah, thank you.

**Comment by ayaankhan98** [comment]
well whosever is the author it does not matter too much the things is that brinary search trees usually follows the principle that nodes with greater values than root goes right of it's root and nodes with value smaller than the root goes left of the root, so if this property is not maintained then we should modify the implementaion to fix the issues.

**Comment by ayaankhan98** [comment]
as far as i remember this file is also modified in #805 if we modifiy this in this PR too, i think there will be a merge conflict, isn't it?

**Comment by kvedala** [comment]
> as far as i remember this file is also modified in #805 if we modifiy this in this PR too, i think there will be a merge conflict, isn't it?

That is quite alright. I will merge the resolution in my branch as there have been cases before. 
I keep my master branch up-to-date with this repo master branch and hence, the conflicts are always resolved on my end.

**Comment by ayaankhan98** [comment]
> > as far as i remember this file is also modified in #805 if we modifiy this in this PR too, i think there will be a merge conflict, isn't it?
> 
> That is quite alright. I will merge the resolution in my branch as there have been cases before.
> I keep my master branch up-to-date with this repo master branch and hence, the conflicts are always resolved on my end.

okay it's alright

**Comment by kvedala** [comment]
solved in #882

**Pull request closed without merging**
