### PR TITLE
created_binary_search_tree_to_linked_list

### PR DESCRIPTION
**Pull request by webdesignbydivyansh**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1362"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
It is recommended to make one PR per file.
This will make the review process much more faster.

Do **not** create any other algorithms in the `operations_on_datastructures` folder, please.

Also, code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

**Comment by webdesignbydivyansh** [comment]
in which directory shall i put my file then?

**Comment by Panquesito7** [comment]
Please delete the `operations_on_datastructures/binary_search_tree_to_linked_list.cpp` file, seems to be a duplicate (in this PR) of  `data_structures/binary_search_tree_to_linked_list.cpp`. Code is different, but same algorithm.

**Comment by webdesignbydivyansh** [comment]
i have closed the pull request

**Pull request closed without merging**
