### PR TITLE
fix: bug in prime number

### PR DESCRIPTION
**Pull request by mrvishalsharma**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1538"></a>

### CODE REVIEW

**Review by mishraabhinn — COMMENTED** [review]
Improve the documentation as well @mrvishalsharma

**Comment by Panquesito7** [comment]
> Improve the documentation

That has to be done in another PR, not in this one.

**Review by Panquesito7 — APPROVED** [review]
Thanks!

**Review by ayaankhan98 — COMMENTED** [review]
It would be nice if you can improve the tests for this file, Including the cases related to this bug.

**Comment by Panquesito7** [comment]
> It would be nice if you could improve the tests for this file

IMO, that should be done in another PR, as this PR is just to fix a bug in the algorithm. But if you folks want it like that, then we can request the PR author to do that. Thanks anyways. 🙂

**Comment by ayaankhan98** [comment]
> > It would be nice if you could improve the tests for this file
> 
> IMO, that should be done in another PR, as this PR is just to fix a bug in the algorithm. But if you folks want it like that, then we can request the PR author to do that. Thanks anyways.

If there is a bug then the author must add tests that cover the cases of that bug. Just to ensure that now things are proper.

**Comment by Panquesito7** [comment]
It seems this is a duplicate of #1537. @ayaankhan98, @mishraabhinn, what should we do? 🤔

**Comment by mishraabhinn** [comment]
> It seems this is a duplicate of #1537. @ayaankhan98, @mishraabhinn, what should we do? 🤔

Accept the pr who raised first :monocle_face:

**Comment by Panquesito7** [comment]
Duplicate of #1537.

**Pull request closed without merging**
