### PR TITLE
Refactor lowest common ancestor

### PR DESCRIPTION
**Pull request by fhlasek**
#### Description of Change

Making the code more modular, following the coding guidelines, flexible, documented and tested.

#909 
#980 

#### Checklist

- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [X] Added tests and example, test must pass
- [X] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [X] Relevant documentation/comments is changed or added
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/981"></a>

### CODE REVIEW

**Comment by fhlasek** [comment]
fixgraph branch seems to be behind master (which this change was originally based on), therefore I opened #982 to bring in the changes.

**Comment by Panquesito7** [comment]
When renaming files, please use the `git move` operation as this will keep file history.
If you remove the file, contributor's and file history will be lost.

**Comment by fhlasek** [comment]
@Panquesito7 not sure if I'm reading the clang-tidy warnings correctly, but it seems to me like they're unrelated to this PR as they're all happening in different files.

**Comment by Panquesito7** [comment]
Yeah, it seems those are issues in another files.
Never mind, then, ignore them unless they are issues in the files you modified.

**Pull request closed without merging**
