### PR TITLE
Added is_graph_bipartite.cpp

### PR DESCRIPTION
**Pull request by AkVaya**
#### Description of Change
Added an algorithm is_graph_bipartite.cpp which determines whether the given graph is a bipartite graph or not.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1011"></a>

### CODE REVIEW

**Comment by AkVaya** [comment]
can someone look into the failing test.

**Comment by kvedala** [comment]
You can click on the the details link to check the exact errors reported by the compiler. 
image

**Comment by kvedala** [comment]
When you are contributing, please include files only related to the pull-request and the description therein. 
Thank you

**Comment by kvedala** [comment]
After reviewing the commit chain, it seems that the following happened and I understand it was not your fault. 

### Description of the error
When you forked the repo, there was an accidental commit by a contributor who did not follow the protocol and hence broke the CI chain. the error reported is due to a file not in your commit chain.
These are the commits recorded as:  c3e0c1a , 2e46077 and a36fd06 and they do not bear your authorship. 

The issue has been rectified as of writing this comment.

# How to resolve
Please rebase your commits to the current master branch of the repo.

Sorry for the inconvenience. Thank you for your contributions 🙂

**Comment by AkVaya** [comment]
The tests are failing due to a problem in the forked breach.
Making a new pull-request.

**Pull request closed without merging**
