### PR TITLE
[fix/docs]: Improve backtracking/n_queens_all_solution_optimised.cpp

### PR DESCRIPTION
**Pull request by Panquesito7**
#### Description of Change

- Improve [`backtracking/n_queens_all_solution_optimised.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/backtracking/n_queens_all_solution_optimised.cpp) with refined code and documentation.

#### Checklist

- [x] Added description of change
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: The https://github.com/TheAlgorithms/C-Plus-Plus/commit/e0fa4f93c3e6116b22ac088d7b10467902baf4c3 commit was made by the CI automatically.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1041"></a>

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1041"></a>

### CODE REVIEW

**Comment by kvedala** [comment]
this is a duplicate of #1049. @Panquesito7 please do not create duplicate PRs.

**Comment by Panquesito7** [comment]
My bad, I thought this wasn't a duplicate.
These are two different files, but with same algorithm.

Sorry any inconveniences!

**Comment by kvedala** [comment]
> My bad, I thought this wasn't a duplicate.
> These are two different files, but with same algorithm.
> 
> Sorry any inconveniences!

Oh, they are different? Would you like this PR to be reviewed and checked once the CI errors are fixed?

**Comment by Panquesito7** [comment]
> like this PR to be reviewed

Sure, if you want; I'll fix CI errors when I got time, thanks. 🙂

**Comment by Panquesito7** [comment]
@kvedala any way how to fix [this error](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1041/checks?check_run_id=1034019168#step:11:45)?

**Comment by ayaankhan98** [comment]
> @kvedala any way how to fix [this error](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1041/checks?check_run_id=1034019168#step:11:45)?

```
error: function-like macro 'inc_loop' used; consider a 'constexpr' template function [cppcoreguidelines-macro-usage,-warnings-as-errors]
#define inc_loop(var, start, stop) for (int var = start; var <= stop; var++)
```
read the error carefully.

**Comment by kvedala** [comment]
> #1041 (comment)

Like @ayaankhan98 replied, you need to replace all the macro functions with the explicit for loops.

**Comment by Panquesito7** [comment]
Continuous integration errors should be fixed now; please re-review again. 🙂

**Comment by kvedala** [comment]
please rebase to resolve the merge conflicts.

**Comment by Panquesito7** [comment]
Rebased (resolved merge conflict).

**Review by kvedala — APPROVED** [review]
LGTM 👍

**Pull request merged**
