### PR TITLE
feat: Add Polynomial Addition

### PR DESCRIPTION
**Pull request by Ankita19ms0010**
#### Checklist

- [ ] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1072"></a>

### CODE REVIEW

**Comment by kvedala** [comment]
This is a very good "C" program and appropriate for the [C-repo](https://github.com/TheAlgorithms/C) as it does not utilize the OOP style and other C++ features. This can also be easily modified to be suitable for C++.

**Comment by Ankita19ms0010** [comment]
Could you please tell me where's the issue in the code formatter? cause I didn't find any errors using clang-tidy. And also please give me some hints so that I can  modify it to be suitable for C++.

**Comment by kvedala** [comment]
image

The errors mentioned are due to the ownership of pointers. In standard C++, the recommendation is to use [unique_ptr](https://en.cppreference.com/w/cpp/memory/unique_ptr), [shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr) and related. The other aspects are to use C++ classes and class-member functions instead of atomic functions. I suggest to keep this as a C program and contribute to the C-repo as mentioned in a previous comment above. 
You can review some examples of analogous C and C++ codes in the two repos. For example:
* Computing Realtime statistical values [in C](https://github.com/TheAlgorithms/C/blob/master/numerical_methods/realtime_stats.c), [in C++](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/realtime_stats.cpp)
* Forward Euler method to solve ODE [in C](https://github.com/TheAlgorithms/C/blob/master/numerical_methods/ode_forward_euler.c), [in C++](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/numerical_methods/ode_forward_euler.cpp)

There are many other codes in both the repo that you can study and learn from.

**Review by rakshaa2000 — CHANGES_REQUESTED** [review]
Please try smart pointers instead, it might pass the automated tests.

**Comment by kvedala** [comment]
This is a duplicate of #600 and only one should be open and accepted

**Pull request closed without merging**
